import os
from langchain_ollama import ChatOllama
from langchain_community.document_loader import TextLoader
from langchain_text_splitters import RecursiveCharacterTextSplitters
from langchain_chroma import Chroma
